"""
Public candidate profiles API.

Exposes public, slug-based profile endpoints like:
    GET /api/public/profiles/{slug}

These are intended to power URLs like:
    https://www.vance.so/{slug}
"""

from typing import Any, Dict, Optional
import time

from fastapi import APIRouter, HTTPException
from fastapi.responses import JSONResponse, Response

from utils.db import fs


router = APIRouter(prefix="/api/public", tags=["Public Profiles"])


def _get_profile_by_slug(slug: str) -> Optional[Dict[str, Any]]:
    """
    Resolve a public slug to a candidate profile payload suitable for the frontend UI.
    """
    # 1. Resolve slug → user_id mapping from public_profiles collection
    mapping_ref = fs.collection("public_profiles").document(slug)
    mapping_doc = mapping_ref.get()

    if not mapping_doc.exists:
        return None

    mapping_data = mapping_doc.to_dict() or {}
    if not mapping_data.get("active", True):
        return None

    user_id = mapping_data.get("user_id")
    if not user_id:
        return None

    # 2. Load canonical profile from user_profiles
    profile_ref = fs.collection("user_profiles").document(user_id)
    profile_doc = profile_ref.get()
    if not profile_doc.exists:
        return None

    profile_data = profile_doc.to_dict() or {}
    extraction_data = profile_data.get("extraction_data", {}) or {}

    name = profile_data.get("name") or extraction_data.get("name") or ""
    linkedin_url = (
        profile_data.get("linkedin_url")
        or extraction_data.get("linkedin_url")
        or ""
    )

    # Core fields for the UI
    role = extraction_data.get("target_role", "")
    experience = extraction_data.get("work_experience", "")
    location = extraction_data.get("current_location", "")

    avatar_url = (
        profile_data.get("avatar_url") or extraction_data.get("avatar_url") or ""
    )

    # Prefer high-signal fields from profile_data (generated by Claude), fallback to extraction_data
    story = (
        profile_data.get("story")
        or extraction_data.get("the_story")
        or extraction_data.get("work_experience")
        or ""
    )

    # Strengths: prefer high-signal generated list, fallback to building from extraction_data
    strengths = profile_data.get("strengths", [])
    if not strengths:
        # Fallback: build from raw extraction fields
        core_skills = extraction_data.get("core_skills")
        if core_skills:
            strengths.append(
                {
                    "text": str(core_skills),
                    "hasAudio": False,
                }
            )

        key_projects = extraction_data.get("key_projects")
        if key_projects:
            strengths.append(
                {
                    "text": str(key_projects),
                    "hasAudio": False,
                }
            )

        motivations = extraction_data.get("motivations")
        if motivations:
            strengths.append(
                {
                    "text": str(motivations),
                    "hasAudio": False,
                }
            )

    # Proof of work: prefer high-signal generated list
    proof_of_work = profile_data.get("proofOfWork", []) or profile_data.get(
        "proof_of_work", []
    )

    # Thoughts: prefer high-signal generated list
    thoughts = profile_data.get("thoughts", [])

    # Audio clips: best-effort – may be empty if not yet attached
    intro_audio_url = profile_data.get("intro_audio_url") or ""
    thinking_audio_url = profile_data.get("thinking_audio_url") or ""
    
    # If audio is stored as conversation_id only (too large for Firestore), return endpoint URL
    audio_conversation_id = profile_data.get("audio_conversation_id") or ""
    audio_available = profile_data.get("audio_available", False)
    
    # CRITICAL: Only use base64 audio URLs if we have a verified conversation_id
    # If base64 audio exists but no conversation_id, we cannot verify ownership - clear it
    has_base64_audio = (intro_audio_url and intro_audio_url.startswith("data:audio")) or (thinking_audio_url and thinking_audio_url.startswith("data:audio"))
    if has_base64_audio and (not audio_conversation_id or audio_conversation_id == "missing"):
        print(f"⚠️ [PROFILE_API] Found base64 audio without conversation_id for {user_id} - cannot verify ownership, clearing base64 audio")
        intro_audio_url = ""
        thinking_audio_url = ""
    
    # Check if we need to construct audio URLs from conversation_id
    # If intro_audio_url is empty/falsy AND we have a valid conversation_id, construct the URLs
    has_valid_audio_url = intro_audio_url and intro_audio_url.strip() and intro_audio_url.startswith(("http://", "https://", "data:"))
    
    # Try to find conversation_id from call history if not in profile
    if not has_valid_audio_url and (not audio_conversation_id or audio_conversation_id == "missing"):
        try:
            calls_ref = fs.collection("user_calls").document(user_id).collection("calls")
            # Try to get recent calls
            try:
                calls = calls_ref.order_by("timestamp", direction="DESCENDING").limit(5).stream()
            except:
                calls = calls_ref.limit(5).stream()
            
            for call_doc in calls:
                call_data = call_doc.to_dict() or {}
                found_conv_id = call_data.get("conversation_id") or call_data.get("call_id")
                if found_conv_id and found_conv_id.strip() and found_conv_id.startswith("conv_"):
                    audio_conversation_id = found_conv_id.strip()
                    print(f"✅ [PROFILE_API] Found conversation_id from call history: {audio_conversation_id}")
                    break
        except Exception as e:
            print(f"⚠️ [PROFILE_API] Error finding conversation_id from call history: {e}")
    
    # Also check if we have a conversation_id stored (even if audio_available is False, try to fetch)
    # CRITICAL: Only return audio if conversation_id is verified to belong to this user
    if not has_valid_audio_url and audio_conversation_id and audio_conversation_id.strip() and audio_conversation_id.startswith("conv_"):
        # Verify ownership before returning audio
        from services.profile_audio_service import profile_audio_service
        is_owner = profile_audio_service._verify_conversation_ownership(audio_conversation_id, user_id)
        
        if is_owner:
            # Audio verified - return endpoint URL for on-demand fetching
            base_url = "https://api.relayy.world"
            intro_audio_url = f"{base_url}/api/public/audio/{audio_conversation_id}?segment=intro"
            thinking_audio_url = f"{base_url}/api/public/audio/{audio_conversation_id}?segment=thinking"
            audio_available = True
            print(f"✅ [PROFILE_API] Verified conversation_id ownership for {user_id}, returning audio URLs")
        else:
            # Audio does not belong to this user - don't return it
            print(f"⚠️ [PROFILE_API] conversation_id={audio_conversation_id} does NOT belong to user_id={user_id}, NOT returning audio")
            intro_audio_url = ""
            thinking_audio_url = ""
            audio_available = False
    
    # Final check: If we have base64 audio URLs, verify they belong to this user via conversation_id
    if (intro_audio_url and intro_audio_url.startswith("data:audio")) or (thinking_audio_url and thinking_audio_url.startswith("data:audio")):
        if not audio_conversation_id or audio_conversation_id == "missing":
            # Base64 audio without conversation_id - cannot verify, don't return
            print(f"⚠️ [PROFILE_API] Base64 audio exists but no conversation_id to verify ownership for {user_id}, clearing audio")
            intro_audio_url = ""
            thinking_audio_url = ""
        else:
            # Verify ownership even for base64 audio
            from services.profile_audio_service import profile_audio_service
            is_owner = profile_audio_service._verify_conversation_ownership(audio_conversation_id, user_id)
            if not is_owner:
                print(f"⚠️ [PROFILE_API] Base64 audio exists but conversation_id does NOT belong to user_id={user_id}, clearing audio")
                intro_audio_url = ""
                thinking_audio_url = ""
                audio_available = False

    # Opportunities section from extraction data
    industries = extraction_data.get("industry_background")
    industries_list = []
    if isinstance(industries, list):
        industries_list = [str(i) for i in industries]
    elif industries:
        industries_list = [str(industries)]

    opportunities = {
        "role": role,
        "industries": industries_list,
        "companyStage": extraction_data.get("company_stage", ""),
    }

    # Verification: If profile exists in public_profiles and is active, it's verified 100%
    # Check if this profile exists in public_profiles (it does since we found it by slug)
    is_verified = mapping_data.get("active", True)  # If we found it by slug, it's active
    
    # If profile is active/verified, set to 100% (score and percentile)
    if is_verified:
        verification_score = 100
        verification_percentile = 100
    else:
        verification_score = profile_data.get("verification_score", 0)
        verification_percentile = profile_data.get("verification_percentile", 0)
    
    verification = {
        "date": profile_data.get("verified_at_display", ""),
        "score": verification_score,
        "percentile": verification_percentile,
    }

    activity = {
        "introductions": profile_data.get("introductions_count", 0),
        "interviewsScheduled": profile_data.get("interviews_scheduled", 0),
        "avgResponseTime": profile_data.get("avg_response_time_display", ""),
    }

    # Demand data – for now driven off introductions count
    demand_data = {
        "introCount": activity["introductions"],
        "days": profile_data.get("activity_window_days", 30),
        "isActive": bool(activity["introductions"]),
    }

    # Final payload shaped to match vance-spotlight/src/pages/Index.tsx expectations
    # Only include fields that have values (filter out empty/missing fields)
    payload = {
        "slug": slug,
        "userId": user_id,
        "name": name,
    }
    
    # Only add fields if they have values
    if role:
        payload["role"] = role
    if experience:
        payload["experience"] = experience
    if location:
        payload["location"] = location
    if avatar_url:
        payload["avatarUrl"] = avatar_url
    if linkedin_url:
        payload["linkedinUrl"] = linkedin_url
    if intro_audio_url:
        payload["introAudioUrl"] = intro_audio_url
    if thinking_audio_url:
        payload["thinkingAudioUrl"] = thinking_audio_url
    if profile_data.get("resume_url"):
        payload["resumeUrl"] = profile_data.get("resume_url")
    if profile_data.get("github_url"):
        payload["githubUrl"] = profile_data.get("github_url")
    
    # Always include demandData, verification, and activity (can be empty/defaults)
    payload["demandData"] = demand_data
    payload["verification"] = verification
    payload["activity"] = activity
    
    # Only add sections if they have content (not empty)
    if story and story.strip():
        payload["story"] = story
    if strengths and len(strengths) > 0:
        payload["strengths"] = strengths
    if proof_of_work and len(proof_of_work) > 0:
        payload["proofOfWork"] = proof_of_work
    if thoughts and len(thoughts) > 0:
        payload["thoughts"] = thoughts
    has_opportunities = (
        (opportunities.get("role") and opportunities["role"].strip()) or
        (opportunities.get("industries") and len(opportunities["industries"]) > 0) or
        (opportunities.get("companyStage") and opportunities["companyStage"].strip())
    )
    if has_opportunities:
        payload["opportunities"] = opportunities
    
    return payload




@router.get("/audio/{conversation_id}")
async def get_audio_by_conversation_id(conversation_id: str, segment: str = "intro"):
    """
    Fetch audio from ElevenLabs by conversation_id.
    Returns trimmed audio segments based on question segments from transcript.
    
    Trimming is based on actual questions asked in the conversation:
    - Intro: Segment where agent asks "tell me about your background" or "tell me about what you're looking for"
    - Thinking: Segment where agent asks "how do you think" or "what do you think" or similar thinking questions
    
    Args:
        conversation_id: ElevenLabs conversation ID
        segment: Audio segment type - "intro" (intro question segment) or "thinking" (thinking question segment)
    """
    from services.profile_audio_service import profile_audio_service
    
    try:
        print(f"🎧 [AUDIO_API] Fetching audio for conversation_id={conversation_id}, segment={segment}")
        
        # Fetch and trim audio based on segment type
        trim_intro = (segment == "intro")
        trim_thinking = (segment == "thinking")
        
        # Find user_id from conversation_id to get transcript
        user_id = None
        try:
            from utils.db import fs
            # Try to find user_id from conversation_id
            # Search for user_id by conversation_id in user_calls (alternative method since collection group might need index)
            # We'll try to find it from user_profiles instead
            profiles_with_conv = fs.collection("user_profiles").where("audio_conversation_id", "==", conversation_id).limit(1).stream()
            for profile_doc in profiles_with_conv:
                user_id = profile_doc.id
                break
        except Exception as e:
            print(f"⚠️ [AUDIO_API] Could not find user_id for conversation_id: {e}")
            # User_id is optional - trimming will use fallback if not found
            pass
        
        intro_audio_url, thinking_audio_url = await profile_audio_service._fetch_audio_from_elevenlabs_api(
            conversation_id, user_id=user_id, trim_intro=trim_intro, trim_thinking=trim_thinking
        )
        
        # Select the appropriate audio segment
        if segment == "intro":
            audio_url = intro_audio_url
        elif segment == "thinking":
            audio_url = thinking_audio_url
        else:
            # Default to intro if invalid segment
            audio_url = intro_audio_url
        
        # If trimming failed, try fetching full audio without trimming
        if not audio_url:
            print(f"⚠️ [AUDIO_API] Trimming failed or returned empty, trying full audio...")
            try:
                intro_audio_url_full, thinking_audio_url_full = await profile_audio_service._fetch_audio_from_elevenlabs_api(
                    conversation_id, user_id=user_id, trim_intro=False, trim_thinking=False
                )
                if segment == "intro":
                    audio_url = intro_audio_url_full or thinking_audio_url_full  # Use any available audio
                elif segment == "thinking":
                    audio_url = thinking_audio_url_full or intro_audio_url_full  # Use any available audio
                else:
                    audio_url = intro_audio_url_full or thinking_audio_url_full
                
                if audio_url:
                    print(f"✅ [AUDIO_API] Successfully fetched full audio as fallback")
            except Exception as e:
                print(f"⚠️ [AUDIO_API] Error fetching full audio: {e}")
        
        if not audio_url:
            print(f"❌ [AUDIO_API] No audio found for {conversation_id}")
            raise HTTPException(status_code=404, detail="Audio not found")
        
        # Extract base64 data from data URL
        if audio_url.startswith("data:audio/mpeg;base64,"):
            base64_data = audio_url.split(",", 1)[1]
            import base64
            audio_bytes = base64.b64decode(base64_data)
            
            print(f"✅ [AUDIO_API] Returning {len(audio_bytes)} bytes of {segment} audio for {conversation_id}")
            
            # Return as MP3 audio file with proper headers
            return Response(
                content=audio_bytes,
                media_type="audio/mpeg",
                headers={
                    "Content-Disposition": f"inline; filename={segment}_audio_{conversation_id}.mp3",
                    "Cache-Control": "public, max-age=3600",
                    "Access-Control-Allow-Origin": "*",  # Allow CORS
                    "Access-Control-Allow-Methods": "GET, OPTIONS",
                }
            )
        else:
            # If it's already a URL, return it as JSON
            return JSONResponse({
                "conversation_id": conversation_id,
                "segment": segment,
                "audio_url": audio_url
            })
    except HTTPException:
        raise
    except Exception as e:
        print(f"❌ [AUDIO_API] Error fetching audio for {conversation_id}: {e}")
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=f"Error fetching audio: {str(e)}")




@router.get("/compensation-card/{uid}")
async def get_compensation_card(uid: str):
    """
    Generate and return a PNG image with the user's compensation band and profile signals.

    This is fetched by WhatsApp when we send the user an image message after their call.
    """
    try:
        from services.compensation_insight_service import (
            compensation_insight_service,
        )

        print(f"🧾 [COMP_CARD_API] Generating compensation card for uid={uid}")

        insights = compensation_insight_service.get_insights(uid)
        png_bytes = compensation_insight_service.render_card_png(uid, insights)

        return Response(
            content=png_bytes,
            media_type="image/png",
            headers={
                "Content-Disposition": f"inline; filename=compensation_card_{uid}.png",
                "Cache-Control": "public, max-age=3600",
                "Access-Control-Allow-Origin": "*",
                "Access-Control-Allow-Methods": "GET, OPTIONS",
            },
        )
    except HTTPException:
        raise
    except Exception as e:
        print(f"❌ [COMP_CARD_API] Error generating compensation card for {uid}: {e}")
        import traceback

        traceback.print_exc()
        raise HTTPException(status_code=500, detail=f"Error generating card: {str(e)}")




@router.get("/profiles/{slug}")
async def get_public_profile(slug: str):
    """
    Public endpoint to fetch a candidate profile by slug.
    """
    profile = _get_profile_by_slug(slug)
    if not profile:
        raise HTTPException(status_code=404, detail="Profile not found")

    response = JSONResponse(profile)
    # Add CORS headers
    response.headers["Access-Control-Allow-Origin"] = "*"
    response.headers["Access-Control-Allow-Methods"] = "GET, OPTIONS"
    response.headers["Access-Control-Allow-Headers"] = "*"
    return response


@router.post("/profiles/{slug}/request-intro")
async def request_intro_from_profile(slug: str, request_data: dict):
    """
    Request an introduction to a candidate from their public profile.
    
    Flow:
    1. Check if requester exists in network by WhatsApp number
    2. If new user: collect name, LinkedIn, initiate voice call
    3. After voice call: send intro request and return WhatsApp link
    
    Request body:
    {
        "whatsapp_number": "1234567890",
        "name": "John Doe" (optional, for new users),
        "linkedin_url": "https://linkedin.com/in/johndoe" (optional, for new users)
    }
    
    Response:
    {
        "status": "existing_user" | "new_user" | "call_initiated" | "call_completed",
        "user_id": "1234567890",
        "is_new_user": true/false,
        "call_status": "pending" | "initiated" | "completed",
        "whatsapp_link": "https://wa.me/..." (after call completes)
    }
    """
    from api.whatsapp_modules.user_recognition import UserRecognitionManager
    from utils.db import get_user_profile, save_data_merge
    import os
    import time
    
    whatsapp_number = request_data.get("whatsapp_number", "").strip()
    country_code = request_data.get("country_code", "").strip()
    name = request_data.get("name", "").strip()
    email = request_data.get("email", "").strip()
    linkedin_url = request_data.get("linkedin_url", "").strip()
    
    if not whatsapp_number:
        raise HTTPException(status_code=400, detail="WhatsApp number is required")
    
    if not name or not email or not linkedin_url:
        raise HTTPException(status_code=400, detail="Name, email, and LinkedIn URL are required")
    
    # Get candidate info from slug
    profile = _get_profile_by_slug(slug)
    if not profile:
        raise HTTPException(status_code=404, detail="Profile not found")
    
    candidate_user_id = profile.get("userId")
    candidate_name = profile.get("name", "this candidate")
    
    if not candidate_user_id:
        raise HTTPException(status_code=404, detail="Candidate user ID not found")
    
    # Normalize WhatsApp number (remove +, spaces, etc.)
    normalized_phone = whatsapp_number.replace("+", "").replace(" ", "").replace("-", "").replace("(", "").replace(")", "")
    
    # Check if user exists
    user_recognition = UserRecognitionManager()
    existing_user = user_recognition.find_user(phone=normalized_phone, wa_id=normalized_phone)
    
    if existing_user:
        # Existing user - check if they have completed onboarding
        user_id = existing_user.get("wa_id") or normalized_phone
        user_profile = get_user_profile(user_id) or {}
        
        # Check if they have name, email, LinkedIn (basic onboarding)
        has_name = user_profile.get("name") or existing_user.get("name")
        has_linkedin = user_profile.get("linkedin_url") or user_profile.get("linkedin")
        has_email = user_profile.get("email") or existing_user.get("email")
        
        if has_name and has_linkedin and has_email:
            # User is fully onboarded - send intro request directly
            try:
                from utils.whatsapp.whatsapp import WhatsAppSender
                from utils.whatsapp.components import MsgComponents
                
                # Get candidate's WhatsApp ID
                candidate_profile_data = get_user_profile(candidate_user_id) or {}
                candidate_wa_id = (
                    candidate_profile_data.get("wa_id")
                    or candidate_profile_data.get("phone")
                    or candidate_profile_data.get("whatsapp")
                    or candidate_user_id
                )
                
                # Send intro request message to candidate
                requester_name = user_profile.get("name", "Someone")
                requester_linkedin = user_profile.get("linkedin_url") or user_profile.get("linkedin") or ""
                
                # Format message: "Name, LinkedIn, has requested intro. Do you want to connect?"
                if requester_linkedin:
                    intro_message = f"{requester_name}, {requester_linkedin}, has requested intro. Do you want to connect?"
                else:
                    intro_message = f"{requester_name} has requested intro. Do you want to connect?"
                
                sender = WhatsAppSender()
                payload = MsgComponents.text_scaffold(to=candidate_wa_id, text=intro_message)
                sender.send(data=payload)
                
                # Save intro request
                intro_request = {
                    "requester_uid": user_id,
                    "requester_name": user_profile.get("name", "Unknown"),
                    "candidate_uid": candidate_user_id,
                    "candidate_name": candidate_name,
                    "status": "pending",
                    "requested_at": time.time(),
                    "source": "profile_page",
                }
                fs.collection("intro_requests").add(intro_request)
                
                # Always use fixed WhatsApp link
                whatsapp_link = "https://shorturl.at/oxUJt"
                
                return JSONResponse({
                    "status": "intro_requested",
                    "user_id": user_id,
                    "is_new_user": False,
                    "whatsapp_link": whatsapp_link,
                    "message": "Intro request sent! Click the link to talk to Vance on WhatsApp."
                })
            except Exception as e:
                print(f"❌ [INTRO_REQUEST] Error sending intro request: {e}")
                import traceback
                traceback.print_exc()
                raise HTTPException(status_code=500, detail=f"Error sending intro request: {str(e)}")
        else:
            # User exists but not fully onboarded - update with new info and send intro request
            # Update user profile with provided info
            save_data_merge(user_id, "users", {
                "name": name if name else user_profile.get("name"),
                "email": email if email else user_profile.get("email"),
                "linkedin_url": linkedin_url if linkedin_url else user_profile.get("linkedin_url"),
                "phone": normalized_phone,
                "wa_id": normalized_phone,
            })
            
            # Now send intro request
            try:
                from utils.whatsapp.whatsapp import WhatsAppSender
                from utils.whatsapp.components import MsgComponents
                
                # Get candidate's WhatsApp ID
                candidate_profile_data = get_user_profile(candidate_user_id) or {}
                candidate_wa_id = (
                    candidate_profile_data.get("wa_id")
                    or candidate_profile_data.get("phone")
                    or candidate_profile_data.get("whatsapp")
                    or candidate_user_id
                )
                
                # Format message: "Name, LinkedIn, has requested intro. Do you want to connect?"
                requester_name = name or user_profile.get("name", "Someone")
                if linkedin_url:
                    intro_message = f"{requester_name}, {linkedin_url}, has requested intro. Do you want to connect?"
                else:
                    intro_message = f"{requester_name} has requested intro. Do you want to connect?"
                
                sender = WhatsAppSender()
                payload = MsgComponents.text_scaffold(to=candidate_wa_id, text=intro_message)
                sender.send(data=payload)
                
                # Save intro request
                intro_request = {
                    "requester_uid": user_id,
                    "requester_name": requester_name,
                    "candidate_uid": candidate_user_id,
                    "candidate_name": candidate_name,
                    "status": "pending",
                    "requested_at": time.time(),
                    "source": "profile_page",
                }
                fs.collection("intro_requests").add(intro_request)
                
                # Always use fixed WhatsApp link
                whatsapp_link = "https://shorturl.at/oxUJt"
                
                return JSONResponse({
                    "status": "intro_requested",
                    "user_id": user_id,
                    "is_new_user": False,
                    "whatsapp_link": whatsapp_link,
                    "message": "Intro request sent! Click the link to talk to Vance on WhatsApp."
                })
            except Exception as e:
                print(f"❌ [INTRO_REQUEST] Error sending intro request: {e}")
                import traceback
                traceback.print_exc()
                raise HTTPException(status_code=500, detail=f"Error sending intro request: {str(e)}")
    else:
        # New user - create user and initiate onboarding
        # Create new user
        try:
            user_data = user_recognition.create_or_update_user(
                wa_id=normalized_phone,
                phone=normalized_phone,
                initial_data={
                    "name": name,
                    "email": email,
                    "linkedin_url": linkedin_url,
                    "connection_type": f"founders hiring {profile.get('role', 'engineers')}",
                    "user_type": "job_provider",  # Requesting intro to candidate = job provider
                    "created_from": "profile_intro_request",
                    "requested_intro_to": candidate_user_id,
                    "requested_intro_to_name": candidate_name,
                }
            )
            
            user_id = user_data.get("wa_id") or normalized_phone
            
            # Save name, email, LinkedIn
            save_data_merge(user_id, "users", {
                "name": name,
                "email": email,
                "linkedin_url": linkedin_url,
                "phone": normalized_phone,
                "wa_id": normalized_phone,
            })
            
            # Initiate voice call
            try:
                from elevenlabs import ConversationInitiationClientDataRequestInput, ElevenLabs
                
                elevenlabs_api_key = os.getenv("ELEVENLABS_API_KEY")
                elevenlabs_agent_id = os.getenv("ELEVENLABS_AGENT_ID")
                elevenlabs_phone_id = os.getenv("ELEVENLABS_PHONE_NUMBER_ID")
                
                if elevenlabs_api_key and elevenlabs_agent_id and elevenlabs_phone_id:
                    elevenlabs_client = ElevenLabs(api_key=elevenlabs_api_key)
                    
                    elevenlabs_client.conversational_ai.twilio.outbound_call(
                        agent_id=elevenlabs_agent_id,
                        agent_phone_number_id=elevenlabs_phone_id,
                        to_number=normalized_phone,
                        conversation_initiation_client_data=ConversationInitiationClientDataRequestInput(
                            user_id=user_id,
                            dynamic_variables={
                                "name": name,
                                "uid": user_id,
                                "user_type": "job_provider",
                                "connection_type": f"founders hiring {profile.get('role', 'engineers')}",
                                "primary_goal": f"connecting with {candidate_name}",
                            },
                        ),
                    )
                    
                    # Track call initiation
                    call_tracking = {
                        "user_id": user_id,
                        "candidate_user_id": candidate_user_id,
                        "candidate_name": candidate_name,
                        "requester_name": name,
                        "requester_linkedin": linkedin_url,
                        "call_initiated_at": time.time(),
                        "status": "initiated",
                        "source": "profile_intro_request",
                    }
                    fs.collection("profile_intro_calls").document(user_id).set(call_tracking)
                    
                    # Always use fixed WhatsApp link
                    whatsapp_link = "https://shorturl.at/oxUJt"
                    
                    return JSONResponse({
                        "status": "call_initiated",
                        "user_id": user_id,
                        "is_new_user": True,
                        "call_status": "initiated",
                        "whatsapp_link": whatsapp_link,
                        "message": "Voice call initiated! Please answer the call to complete your onboarding."
                    })
                else:
                    raise HTTPException(status_code=500, detail="Voice calling not configured")
            except Exception as e:
                print(f"❌ [INTRO_REQUEST] Error initiating call: {e}")
                import traceback
                traceback.print_exc()
                raise HTTPException(status_code=500, detail=f"Error initiating call: {str(e)}")
                
        except Exception as e:
            print(f"❌ [INTRO_REQUEST] Error creating user: {e}")
            import traceback
            traceback.print_exc()
            raise HTTPException(status_code=500, detail=f"Error creating user: {str(e)}")


@router.get("/profiles/{slug}/intro-status/{user_id}")
async def get_intro_request_status(slug: str, user_id: str):
    """
    Check the status of an intro request and voice call.
    
    Returns:
    {
        "call_status": "initiated" | "completed" | "not_found",
        "intro_requested": true/false,
        "whatsapp_link": "https://wa.me/..." (if call completed)
    }
    """
    try:
        # Check call status
        call_doc = fs.collection("profile_intro_calls").document(user_id).get()
        call_status = "not_found"
        intro_requested = False
        
        if call_doc.exists:
            call_data = call_doc.to_dict() or {}
            call_status = call_data.get("status", "initiated")
            
            # Check if call has completed (look for extraction data or call completion)
            extraction_doc = fs.collection("extractions").document(user_id).get()
            if extraction_doc.exists:
                call_status = "completed"
                intro_requested = call_data.get("intro_requested", False)
        
        # Get candidate user_id from slug
        profile = _get_profile_by_slug(slug)
        if not profile:
            raise HTTPException(status_code=404, detail="Profile not found")
        
        candidate_user_id = profile.get("userId")
        
        # Always use fixed WhatsApp link
        whatsapp_link = "https://shorturl.at/oxUJt"
        
        if call_status == "completed":
            # Check if intro was already requested
            intro_requests = fs.collection("intro_requests").where("requester_uid", "==", user_id).where("candidate_uid", "==", candidate_user_id).limit(1).stream()
            intro_requested = any(True for _ in intro_requests)
            
            if not intro_requested:
                # Auto-send intro request after call completion
                try:
                    from utils.whatsapp.whatsapp import WhatsAppSender
                    from utils.whatsapp.components import MsgComponents
                    from utils.db import get_user_profile
                    
                    user_profile = get_user_profile(user_id) or {}
                    requester_name = user_profile.get("name", "Someone")
                    requester_linkedin = user_profile.get("linkedin_url") or user_profile.get("linkedin") or ""
                    
                    # Get candidate's WhatsApp ID
                    candidate_profile_data = get_user_profile(candidate_user_id) or {}
                    candidate_wa_id = (
                        candidate_profile_data.get("wa_id")
                        or candidate_profile_data.get("phone")
                        or candidate_profile_data.get("whatsapp")
                        or candidate_user_id
                    )
                    
                    # Format message: "Name, LinkedIn, has requested intro. Do you want to connect?"
                    if requester_linkedin:
                        intro_message = f"{requester_name}, {requester_linkedin}, has requested intro. Do you want to connect?"
                    else:
                        intro_message = f"{requester_name} has requested intro. Do you want to connect?"
                    
                    sender = WhatsAppSender()
                    payload = MsgComponents.text_scaffold(to=candidate_wa_id, text=intro_message)
                    sender.send(data=payload)
                    
                    # Save intro request
                    intro_request = {
                        "requester_uid": user_id,
                        "requester_name": requester_name,
                        "candidate_uid": candidate_user_id,
                        "candidate_name": profile.get("name", "Candidate"),
                        "status": "pending",
                        "requested_at": time.time(),
                        "source": "profile_page",
                    }
                    fs.collection("intro_requests").add(intro_request)
                    
                    # Update call tracking
                    fs.collection("profile_intro_calls").document(user_id).update({
                        "intro_requested": True,
                        "intro_requested_at": time.time(),
                    })
                    
                    intro_requested = True
                except Exception as e:
                    print(f"⚠️ [INTRO_REQUEST] Error auto-sending intro request: {e}")
        
        # Always return fixed WhatsApp link
        return JSONResponse({
            "call_status": call_status,
            "intro_requested": intro_requested,
            "whatsapp_link": "https://shorturl.at/oxUJt" if call_status == "completed" else None,
        })
    except Exception as e:
        print(f"❌ [INTRO_REQUEST] Error checking status: {e}")
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=f"Error checking status: {str(e)}")


